package dev.whisper.voice

object Constants {
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"
    const val ACTION_DISCONNECT = "ACTION_DISCONNECT"
    const val ACTION_MUTE_MIC = "ACTION_MUTE_MIC"
    const val ACTION_UNMUTE_MIC = "ACTION_UNMUTE_MIC"
    const val ACTION_MUTE_SPK = "ACTION_MUTE_SPK"
    const val ACTION_UNMUTE_SPK = "ACTION_UNMUTE_SPK"

    const val NOTIFICATION_CHANNEL_ID = "INCHATTING_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "INCHATTING_NOTIFICATION_NAME"
    const val NOTIFICATION_ID = 10

    const val INCHATTING_ACTIONS = "INCHATTING_ACTIONS"

    const val TO_WHISPER_REQUEST_CODE = 99
    const val MUTE_MIC_REQUEST_CODE = 100
    const val MUTE_SPK_REQUEST_CODE = 101
    const val UNMUTE_MIC_REQUEST_CODE = 102
    const val UNMUTE_SPK_REQUEST_CODE = 103
    const val DISCONNECT_REQUEST_CODE = 104

    const val SERVER_NAME = "SERVER_NAME"
    const val CHANNEL_NAME = "CHANNEL_NAME"
}
